# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f9fd176caffced993894c5dbcef8522a2d2570c673f00d7f292702128f9808b479a749bcc10c4f3d403383e108b97d7ddb107441831074e487012baa2bf2e571

test:
  secret_key_base: f4e39b3fc5e9b5269d539b5cfa1e2c292ddb20719bea541e7167459ac5798976e3d67c3894473ba28406568fedf282b2b800d04da27502d5547d9445e86acd07

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
